### ISSUE TITLE
Python3 error

### ISSUE THREAD

**Issue by piotor87** [getian107/PRScs#10]
I've tried running the same pipeline with python3 and python2. Python2 works perfectly, but with python3 i get the following error for some chromosomes:

`Traceback (most recent call last):
  File "/home/pete/Dropbox/Projects/CS-PRS-pipeline/PRScs/PRScs.py", line 163, in <module>
    main()
  File "/home/pete/Dropbox/Projects/CS-PRS-pipeline/PRScs/PRScs.py", line 156, in main
    param_dict['n_iter'], param_dict['n_burnin'], param_dict['thin'], int(chrom), param_dict['out_dir'], param_dict['beta_std'], param_dict['seed'])
  File "/home/pete/Dropbox/Projects/CS-PRS-pipeline/PRScs/mcmc_gtb.py", line 67, in mcmc
    psi[jj] = gigrnd.gigrnd(a-0.5, 2.0*delta[jj], n*beta[jj]**2/sigma)
  File "/home/pete/Dropbox/Projects/CS-PRS-pipeline/PRScs/gigrnd.py", line 66, in gigrnd
    s = min(1/lam, math.log(1+1/alpha+math.sqrt(1/math.pow(alpha,2)+2/alpha)))
`

**Comment by getian107** [comment]
Was that a ZeroDivisionError? If yes, that was fixed very recently. You can pull the latest version and try again.

**Comment by piotor87** [comment]
Yep. that was it. I've been testing it for the last week, glad you got there first!
