### ISSUE TITLE
ZeroDivisionError 

### ISSUE THREAD

**Issue by biostat0903** [getian107/PRScs#14]
Hi Tian, 
Using the newest version, I make the reference panel by my data. But PRScs still have the ZeroDivisionError. 
When I use 1kg reference panel by you, do not have the problem. 
````bash
... MCMC ...
Traceback (most recent call last):
  File "/net/mulan/home/yasheng/comparisonProject/program/PRScs-master/PRScs.py", line 160, in <module>
    main()
  File "/net/mulan/home/yasheng/comparisonProject/program/PRScs-master/PRScs.py", line 154, in main
    param_dict['n_iter'], param_dict['n_burnin'], param_dict['thin'], int(chrom), param_dict['out_dir'], param_dict['beta_std'], param_dict['seed'])
  File "/net/mulan/home/yasheng/comparisonProject/program/PRScs-master/mcmc_gtb.py", line 67, in mcmc
    psi[jj] = gigrnd.gigrnd(a-0.5, 2.0*delta[jj], n*beta[jj]**2/sigma)
  File "/net/mulan/home/yasheng/comparisonProject/program/PRScs-master/gigrnd.py", line 102, in gigrnd
    rnd = math.exp(rnd)*(lam/omega+math.sqrt(1+math.pow(lam,2)/math.pow(omega,2)))
ZeroDivisionError: float division by zero
````
Best, 
Sheng

**Comment by getian107** [comment]
Hi Sheng- I think the problem likely lies in "snpinfo_1kg_hm3". You need to create a new "snpinfo_1kg_hm3" with a list of SNPs that match *exactly* with the reference panel you created (i.e., the same number of SNPs in the same order with matched A1 allele).

**Comment by biostat0903** [comment]
Hi Tian, 
I check the "snpinfo_1kg_hm3" and the reference panel. The SNPs are matched. 
My code is :
````R
#! /usr/bin/env Rscript
rm(list=ls())
library(bigreadr)
library(plyr)
library(optparse)

## Input parameters
args_list = list(
  make_option("--chr", type="numeric", default=NULL,
              help="INPUT: gemma file", metavar="character")
)

opt_parser = OptionParser(option_list=args_list)
opt = parse_args(opt_parser)

chr = opt$chr

## set parameters
comp_str <- "/net/mulan/disk2/yasheng/comparisonProject/"
hm3_str <- paste0(comp_str, "04_reference/Hapmap3/")
blk_str <- paste0(hm3_str, "blk/")
blk_info <- fread2(paste0(comp_str, "LDblock/chr", chr, ".bed"), select = c(2, 3))
chr_str <- paste0(hm3_str, "geno/chr", chr)
chr_bim <- fread2(paste0(chr_str, ".bim"), select = c(2, 4, 5, 6))
blk_snp_dat <- aaply(c(1: nrow(blk_info)), 1, function(a) 
  ifelse(chr_bim[, 2]>blk_info[a, 1] & chr_bim[, 2]<=blk_info[a, 2], a, 0))
chr_snp <- vector()

for (b in 1: nrow(blk_info)){

  ## get LD matrix
  blk_b_str <- paste0(blk_str, "chr", chr, "_blk", b)
  snp_blk <- chr_bim[blk_snp_dat[b, ] == b, 1]
  write.table(snp_blk, file = paste0(blk_b_str, ".snp"),
              row.names = F, col.names = F, quote = F)
  LD_cmd <- paste0("plink-1.9 --silent --bfile ", chr_str, " --r square ",
                    " --extract ", blk_b_str, ".snp --out ", blk_b_str)
  system(LD_cmd)
  chr_snp <- c(chr_snp, snp_blk)

  ## remove files
  system(paste0("rm ", blk_b_str, ".log"))
  cat ("blk", b, "is finished!\n")
}

## get MAF
frq_cmd <- paste0("plink-1.9 --silent --bfile ", chr_str,
                  " --freq --out ", chr_str)
system(frq_cmd)
system(paste0("rm ", chr_str, ".log"))

chr_frq <- fread2(paste0(chr_str, ".frq"), select = c(1, 2, 3, 4, 5))
chr_frq <- cbind(chr_frq[, c(1, 2)], chr_bim[, 2], chr_frq[, -c(1, 2)])
chr_frq <- chr_frq[chr_frq[, 2] %in% chr_snp, ]
cat ("chr ", opt$chr, ": ", nrow(chr_frq), "snps.\n")
if (chr < 10){
  write.table(chr_frq, file = paste0(hm3_str, "/ldblk_1kg_eur/snpinfo_1kg_hm3_chr0", chr), 
              row.names = F, col.names = F, quote = F, sep = "\t")
} else {
  write.table(chr_frq, file = paste0(hm3_str, "/ldblk_1kg_eur/snpinfo_1kg_hm3_chr", chr), 
              row.names = F, col.names = F, quote = F, sep = "\t")
}
````
Best, 
Sheng

**Comment by getian107** [comment]
Hi Sheng- Any chance you can transfer your reference panel, snpinfo_1kg_hm3 and GWAS summary statistics (data for the chromosome which produced the error) to me (e.g., via Dropbox) so I can take a look? It’s hard to figure out what’s going wrong without seeing the data.

**Comment by biostat0903** [comment]
Hi, 
I have sent you an email to you (tge1@mgh.harvard.edu). Do you receive it?
Thanks for your fast reply.

Best, 
Sheng

**Comment by getian107** [comment]
Hi Sheng- I haven't received your email. Could you resend and cc my gmail (getion107@gmail.com) as well? Thanks!

**Comment by getian107** [comment]
Sorry- these was a typo in the gmail address I provided; the correct one is: getian107@gmail.com

**Comment by getian107** [comment]
Hi Sheng- I think as I mentioned the issue is that SNPs in snpinfo_1kg_hm3 did not match SNPs in your LD reference panel. For example, rs5996529 is in snpinfo_1kg_hm3 but doesn't seem to be included when calculating the LD matrices. Please double check to make sure SNPs in these two files match exactly.

**Comment by biostat0903** [comment]
Hi Tian, 
Thanks for your kindly reply. 
I have fixed the bug. 
Best,
Sheng
