### ISSUE TITLE
UnboundLocalError: local variable 'ref_dict' referenced before assignment

### ISSUE THREAD

**Issue by petertanksley** [getian107/PRScs#33]
Hello, Tian!
I am running the following code:

```
export PATH=$PATH:/scratch/07624/tankslpr/TUTORIALS/PRScs

module load python2
module load phdf5/1.8.16
PRScs.py --ref_dir=../../../../TUTORIALS/PRScs/REF_PANEL/ldblk_1kg_eur/ \
         --bim_prefix=../../../../TT_GENOTYPES/TEXAS_TWINS.1KG.EUR_noOutliers.chr1_22.updated.SNPs.maf1e-3.hwe1e-6.info90 \
         --sst_file=../../INPUT/0_raw/3_CRP_1KG_GWAS_AJHG_2018_PRScs.txt \
         --n_gwas=148164 \
         --seed=973101 \
         --out_dir=../../OUTPUT
```

The job begins running but quickly terminates with an error. The log file reads as follows:
```
--phi=None
--n_gwas=148164
--seed=973101
--sst_file=../../INPUT/0_raw/3_CRP_1KG_GWAS_AJHG_2018_PRScs.txt
--chrom=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
--a=1
--bim_prefix=../../../../TT_GENOTYPES/TEXAS_TWINS.1KG.EUR_noOutliers.chr1_22.updated.SNPs.maf1e-3.hwe1e-6.info90
--b=0.5
--beta_std=False
--n_iter=1000
--out_dir=../../OUTPUT
--thin=5
--ref_dir=../../../../TUTORIALS/PRScs/REF_PANEL/ldblk_1kg_eur/
--n_burnin=500


##### process chromosome 1 #####
... parse bim file: ../../../../TT_GENOTYPES/TEXAS_TWINS.1KG.EUR_noOutliers.chr1_22.updated.SNPs.maf1e-3.hwe1e-6.info90.bim ...
... 360694 SNPs on chromosome 1 read from ../../../../TT_GENOTYPES/TEXAS_TWINS.1KG.EUR_noOutliers.chr1_22.updated.SNPs.maf1e-3.hwe1e-6.info90.bim ...
Traceback (most recent call last):
  File "/scratch/07624/tankslpr/TUTORIALS/PRScs/PRScs.py", line 167, in <module>
    main()
  File "/scratch/07624/tankslpr/TUTORIALS/PRScs/PRScs.py", line 156, in main
    sst_dict = parse_genet.parse_sumstats(ref_dict, vld_dict, param_dict['sst_file'], param_dict['n_gwas'])
UnboundLocalError: local variable 'ref_dict' referenced before assignment
```
I think I am using the standard format for calling PRScs, so I am a little unsure where the program is getting confused about the assignment of the `ref_dict` local variable. Any help would be appreciated!

**Comment by getian107** [comment]
I think if you remove the "/" after `ldblk_1kg_eur` the program would work. Sorry for coding this in a not very flexible way.

**Comment by petertanksley** [comment]
Thanks for the tip!
It ran after after removing the "/" but now it is producing similar error for beta_std (a parameter I did not specify). Any thoughts? Thanks!

```
--phi=None
--n_gwas=148164
--seed=973101
--sst_file=../../INPUT/0_raw/3_CRP_1KG_GWAS_AJHG_2018_PRScs.txt
--chrom=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
--a=1
--bim_prefix=../../../../TT_GENOTYPES/TEXAS_TWINS.1KG.EUR_noOutliers.chr1_22.updated.SNPs.maf1e-3.hwe1e-6.info90
--b=0.5
--beta_std=False
--n_iter=1000
--out_dir=../../OUTPUT
--thin=5
--ref_dir=../../../../TUTORIALS/PRScs/REF_PANEL/ldblk_1kg_eur
--n_burnin=500


##### process chromosome 1 #####
... parse reference file: ../../../../TUTORIALS/PRScs/REF_PANEL/ldblk_1kg_eur/snpinfo_1kg_hm3 ...
... 92617 SNPs on chromosome 1 read from ../../../../TUTORIALS/PRScs/REF_PANEL/ldblk_1kg_eur/snpinfo_1kg_hm3 ...
... parse bim file: ../../../../TT_GENOTYPES/TEXAS_TWINS.1KG.EUR_noOutliers.chr1_22.updated.SNPs.maf1e-3.hwe1e-6.info90.bim ...
... 360694 SNPs on chromosome 1 read from ../../../../TT_GENOTYPES/TEXAS_TWINS.1KG.EUR_noOutliers.chr1_22.updated.SNPs.maf1e-3.hwe1e$
... parse sumstats file: ../../INPUT/0_raw/3_CRP_1KG_GWAS_AJHG_2018_PRScs.txt ...
... 9227898 SNPs read from ../../INPUT/0_raw/3_CRP_1KG_GWAS_AJHG_2018_PRScs.txt ...
... 54539 common SNPs in the reference, sumstats, and validation set ...
Traceback (most recent call last):
  File "/scratch/07624/tankslpr/TUTORIALS/PRScs/PRScs.py", line 167, in <module>
    main()
  File "/scratch/07624/tankslpr/TUTORIALS/PRScs/PRScs.py", line 156, in main
    sst_dict = parse_genet.parse_sumstats(ref_dict, vld_dict, param_dict['sst_file'], param_dict['n_gwas'])
  File "/scratch/07624/tankslpr/TUTORIALS/PRScs/parse_genet.py", line 112, in parse_sumstats
    beta_std = -1*sp.sign(beta)*abs(norm.ppf(p/2.0))/n_sqrt
UnboundLocalError: local variable 'beta' referenced before assignment 
```

**Comment by getian107** [comment]
Could you show the first few lines of the GWAS summary statistics file?

**Comment by petertanksley** [comment]
Here we go:
```
rsid   A1   A2   b   p
rs2190002   A   G   1e-04   0.981867820961016
rs6698308   A   G   -0.0055   0.432034892005007
rs149779215   A   G   -0.0019   0.88724505783322
rs17018613   A   G   -0.001   0.841480581121794
rs4950403   T   C   -0.0132   0.00595952647010911
rs17024750   A   G   -0.0086   0.232304160207264
rs12822012   A   C   -3e-04   0.958748503692605
rs6504640   T   C   -0.0031   0.50952694326248
rs12453078   C   G   -0.0118   0.00400143259166327
```

**Comment by getian107** [comment]
The headline must be SNP, A1, A2, BETA and P

**Comment by petertanksley** [comment]
Yup, so simple. Thanks for the help, Tian! It appears to be running just fine now.
