### ISSUE TITLE
--ref_dir parsing issue

### ISSUE THREAD

**Issue by vaqm2** [getian107/PRScs#35]
Hi Tian,

I'm trying to implement PRS-CS as part of a polygenic scoring analysis pipeline along with various other prediction methods. The pipeline is designed using Nextflow and I'm having an issue with the way the ref_dir option is being parsed in the code.

Especially, I think this section:

```
        if '1kg' in os.path.basename(param_dict['ref_dir']):
            ref_dict = parse_genet.parse_ref(param_dict['ref_dir'] + '/snpinfo_1kg_hm3', int(chrom))
        elif 'ukbb' in os.path.basename(param_dict['ref_dir']):
            ref_dict = parse_genet.parse_ref(param_dict['ref_dir'] + '/snpinfo_ukbb_hm3', int(chrom))
```

Since Nextflow and other workflow languages stage the files for each process being run, the directory name is often generated at random and they do not have the 1kg or ukbb in the path name and in such situations, the code seems to error out.

For example, from a nextflow run:

```
python PRScs.py --ref_dir=/pgs_devel/people/viveka/work/a5/21253093de9ec48431887239c246e4 --bim_prefix=Genomes1k_Phase1_CEU --sst_file=ieu-b-42_prscs_chr22.txt --n_gwas=77096 --chrom=22 --out_dir=ieu-b-42


--ref_dir=/pgs_devel/people/viveka/work/a5/21253093de9ec48431887239c246e4
--bim_prefix=Genomes1k_Phase1_CEU
--sst_file=ieu-b-42_prscs_chr22.txt
--a=1
--b=0.5
--phi=None
--n_gwas=77096
--n_iter=1000
--n_burnin=500
--thin=5
--out_dir=ieu-b-42
--chrom=['22']
--beta_std=False
--seed=None


##### process chromosome 22 #####
... parse bim file: Genomes1k_Phase1_CEU.bim ...
... 494324 SNPs on chromosome 22 read from Genomes1k_Phase1_CEU.bim ...
Traceback (most recent call last):
  File "/pgs_devel/people/viveka/work/a5/21253093de9ec48431887239c246e4/PRScs.py", line 167, in <module>
    main()
  File "/pgs_devel/people/viveka/work/a5/21253093de9ec48431887239c246e4/PRScs.py", line 156, in main
    sst_dict = parse_genet.parse_sumstats(ref_dict, vld_dict, param_dict['sst_file'], param_dict['n_gwas'])
UnboundLocalError: local variable 'ref_dict' referenced before assignment
```

Can the --ref_dir command line option parsing be modified to accommodate such usage scenarios? It would be very helpful in my case if I could specify the LD matrix as well as SNP info file on the command line itself, instead of specifying the directory path and letting the script parse the file name.

Appreciate the help,
Vivek.

**Comment by vaqm2** [comment]
Please ignore, I found a workaround by creating a dummy directory in the nextflow process with the required matching regex and moving the staged files there.
